[uwsgi]
module = main:app
master = true
processes = 4
socket = /tmp/uwsgi.sock
chmod-socket = 660
vacuum = true
die-on-term = true
enable-threads = true
single-interpreter = true
http-auto-chunked = true
http-keepalive = true
add-header = Connection: Keep-Alive
lazy-apps = true
chdir = /home/pi/garageController
protocol = http